---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hazelcast-jet-helm-client-configuration
data:
  hazelcast-client.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <hazelcast-client xsi:schemaLocation="http://www.hazelcast.com/schema/client-config hazelcast-client-config-3.10.xsd"
                      xmlns="http://www.hazelcast.com/schema/client-config"
                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <properties>
        <property name="hazelcast.discovery.enabled">true</property>
      </properties>
      <network>
        <discovery-strategies>
          <discovery-strategy enabled="true" class="com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy">
              <properties>
                <!-- Put your Hazelcast Jet service name create by helm, here. -->
                <property name="service-name">first-release-hazelcast-jet</property>
                <property name="namespace">default</property>
              </properties>
          </discovery-strategy>
        </discovery-strategies>
      </network>
    </hazelcast-client>
---
apiVersion: batch/v1
kind: Job
metadata:
  name: rolling-aggregation
spec:
  template:
    spec:
      containers:
      - name: rolling-aggregation
        image: rolling-aggregation:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: "/config/hazelcast-jet/"
            name: hazelcast-jet-config-storage
        env:
          - name: JAVA_TOOL_OPTIONS
            value: "-Dhazelcast.client.config=/config/hazelcast-jet/hazelcast-client.xml"
      volumes:
      - name: hazelcast-jet-config-storage
        configMap:
          name: hazelcast-jet-helm-client-configuration
          items:
            - key: hazelcast-client.xml
              path: hazelcast-client.xml
      restartPolicy: OnFailure
